In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(size=(3,4,5))
x

tensor([[[0.9445, 0.8510, 0.5991, 0.1757, 0.4707],
         [0.5475, 0.6719, 0.8362, 0.4766, 0.2399],
         [0.5042, 0.0862, 0.0833, 0.8345, 0.0112],
         [0.2634, 0.6539, 0.4357, 0.2196, 0.7293]],

        [[0.0862, 0.0031, 0.2906, 0.4413, 0.0330],
         [0.3245, 0.0199, 0.3099, 0.9257, 0.0515],
         [0.3553, 0.7584, 0.3399, 0.4410, 0.3972],
         [0.8283, 0.6199, 0.1360, 0.3594, 0.5745]],

        [[0.6427, 0.7812, 0.7549, 0.3777, 0.8071],
         [0.6134, 0.7595, 0.6038, 0.5526, 0.2116],
         [0.6285, 0.0320, 0.8600, 0.6047, 0.8718],
         [0.2614, 0.7397, 0.8610, 0.1605, 0.9138]]])

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x.resize_(6,10)

tensor([[0.9445, 0.8510, 0.5991, 0.1757, 0.4707, 0.5475, 0.6719, 0.8362, 0.4766,
         0.2399],
        [0.5042, 0.0862, 0.0833, 0.8345, 0.0112, 0.2634, 0.6539, 0.4357, 0.2196,
         0.7293],
        [0.0862, 0.0031, 0.2906, 0.4413, 0.0330, 0.3245, 0.0199, 0.3099, 0.9257,
         0.0515],
        [0.3553, 0.7584, 0.3399, 0.4410, 0.3972, 0.8283, 0.6199, 0.1360, 0.3594,
         0.5745],
        [0.6427, 0.7812, 0.7549, 0.3777, 0.8071, 0.6134, 0.7595, 0.6038, 0.5526,
         0.2116],
        [0.6285, 0.0320, 0.8600, 0.6047, 0.8718, 0.2614, 0.7397, 0.8610, 0.1605,
         0.9138]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
y = torch.randint(9, size=(10,))
y

tensor([4, 8, 6, 3, 6, 2, 7, 4, 1, 7])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
x_plus_y = x+y
x_plus_y

tensor([[4.9445, 8.8510, 6.5991, 3.1757, 6.4707, 2.5475, 7.6719, 4.8362, 1.4766,
         7.2399],
        [4.5042, 8.0862, 6.0833, 3.8345, 6.0112, 2.2634, 7.6539, 4.4357, 1.2196,
         7.7293],
        [4.0862, 8.0031, 6.2906, 3.4413, 6.0330, 2.3245, 7.0199, 4.3099, 1.9257,
         7.0515],
        [4.3553, 8.7584, 6.3399, 3.4410, 6.3972, 2.8283, 7.6199, 4.1360, 1.3594,
         7.5745],
        [4.6427, 8.7812, 6.7549, 3.3777, 6.8071, 2.6134, 7.7595, 4.6038, 1.5526,
         7.2116],
        [4.6285, 8.0320, 6.8600, 3.6047, 6.8718, 2.2614, 7.7397, 4.8610, 1.1605,
         7.9138]])

In [7]:
x_plus_y.shape

torch.Size([6, 10])

In [8]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
new_mtrx = torch.matmul(x_plus_y, x_plus_y.T)
new_mtrx

tensor([[341.6251, 328.7589, 317.0359, 335.7286, 342.9851, 342.8163],
        [328.7589, 318.1297, 305.8095, 323.9302, 330.2426, 331.1606],
        [317.0359, 305.8095, 295.2486, 312.1302, 318.6624, 318.7883],
        [335.7286, 323.9302, 312.1302, 331.0283, 337.4196, 337.3598],
        [342.9851, 330.2426, 318.6624, 337.4196, 344.6919, 344.5293],
        [342.8163, 331.1606, 318.7883, 337.3598, 344.5293, 345.8322]])

In [9]:
new_mtrx.shape

torch.Size([6, 6])

In [10]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
coord_01 = torch.FloatTensor((1, 0.5, 2))
ort_3 = torch.ones(size=(3,), requires_grad=True)


In [11]:
func_02 = ort_3**3 + ort_3 - 75*ort_3
func_02

tensor([-73., -73., -73.], grad_fn=<SubBackward0>)

In [12]:
deriv_func_01 = func_02.backward(ort_3)

In [13]:
print(deriv_func_01)

None


In [14]:
# 8. Создайте единичный тензор размера 5x6
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
# 9. Переведите его в формат numpy
np_arr = ones.numpy()
np_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)