In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(size=(3,4,5))
x

tensor([[[0.5667, 0.5470, 0.3554, 0.4086, 0.8570],
         [0.0939, 0.1377, 0.5745, 0.1992, 0.0824],
         [0.6950, 0.7641, 0.9080, 0.2301, 0.0656],
         [0.7515, 0.4881, 0.2425, 0.7235, 0.5737]],

        [[0.5372, 0.6494, 0.1120, 0.0912, 0.7456],
         [0.1579, 0.5938, 0.6351, 0.7649, 0.4906],
         [0.6524, 0.5694, 0.0588, 0.0167, 0.4460],
         [0.7230, 0.0778, 0.6268, 0.5273, 0.6845]],

        [[0.2573, 0.2114, 0.3715, 0.9387, 0.7023],
         [0.8983, 0.4720, 0.0455, 0.1839, 0.7706],
         [0.5974, 0.6262, 0.0933, 0.1117, 0.4324],
         [0.2438, 0.1951, 0.6520, 0.9054, 0.3482]]])

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x.resize_(6,10)

tensor([[0.5667, 0.5470, 0.3554, 0.4086, 0.8570, 0.0939, 0.1377, 0.5745, 0.1992,
         0.0824],
        [0.6950, 0.7641, 0.9080, 0.2301, 0.0656, 0.7515, 0.4881, 0.2425, 0.7235,
         0.5737],
        [0.5372, 0.6494, 0.1120, 0.0912, 0.7456, 0.1579, 0.5938, 0.6351, 0.7649,
         0.4906],
        [0.6524, 0.5694, 0.0588, 0.0167, 0.4460, 0.7230, 0.0778, 0.6268, 0.5273,
         0.6845],
        [0.2573, 0.2114, 0.3715, 0.9387, 0.7023, 0.8983, 0.4720, 0.0455, 0.1839,
         0.7706],
        [0.5974, 0.6262, 0.0933, 0.1117, 0.4324, 0.2438, 0.1951, 0.6520, 0.9054,
         0.3482]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
y = torch.randint(9, size=(10,))
y

tensor([1, 4, 7, 3, 8, 7, 6, 8, 3, 4])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
x_plus_y = x+y
x_plus_y

tensor([[1.5667, 4.5470, 7.3554, 3.4086, 8.8570, 7.0939, 6.1377, 8.5745, 3.1992,
         4.0824],
        [1.6950, 4.7641, 7.9080, 3.2301, 8.0656, 7.7515, 6.4881, 8.2425, 3.7235,
         4.5737],
        [1.5372, 4.6494, 7.1120, 3.0912, 8.7456, 7.1579, 6.5938, 8.6351, 3.7649,
         4.4906],
        [1.6524, 4.5694, 7.0588, 3.0167, 8.4460, 7.7230, 6.0778, 8.6268, 3.5273,
         4.6845],
        [1.2573, 4.2114, 7.3715, 3.9387, 8.7023, 7.8983, 6.4720, 8.0455, 3.1839,
         4.7706],
        [1.5974, 4.6262, 7.0933, 3.1117, 8.4324, 7.2438, 6.1951, 8.6520, 3.9054,
         4.3482]])

In [7]:
x_plus_y.shape

torch.Size([6, 10])

In [8]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
new_mtrx = torch.matmul(x_plus_y, x_plus_y.T)
new_mtrx

tensor([[355.7136, 361.0016, 359.5234, 356.8434, 360.2413, 354.8458],
        [361.0016, 368.4985, 365.5192, 363.2218, 366.6054, 360.9930],
        [359.5234, 365.5192, 364.2196, 361.3428, 364.3151, 359.4166],
        [356.8434, 363.2218, 361.3428, 359.2636, 362.0557, 356.8351],
        [360.2413, 366.6054, 364.3151, 362.0557, 366.7950, 359.5124],
        [354.8458, 360.9930, 359.4166, 356.8351, 359.5124, 354.9234]])

In [9]:
new_mtrx.shape

torch.Size([6, 6])

In [10]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
#drv_y(x) = 3x**2, drv_y(z) = 1, drv_y(t) = 75  => in point (1, 0.5, 2) deriv = (3, 1, -75)
point_x = torch.tensor([1.], requires_grad=True)
point_z = torch.tensor([0.5], requires_grad=True)
point_t = torch.tensor([2.], requires_grad=True)
ort_1 = torch.ones(size=(1,), requires_grad=True)

In [11]:
h = point_x**3 + point_z - 75 * point_t

In [12]:
h.backward(ort_1)

In [13]:
print(f' y function derivative in point with coordinates: \n x = {point_x.grad}\n z = {point_z.grad}\n t = {point_t.grad}')

 y function derivative in point with coordinates: 
 x = tensor([3.])
 z = tensor([1.])
 t = tensor([-75.])


In [14]:
# 8. Создайте единичный тензор размера 5x6
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
# 9. Переведите его в формат numpy
np_arr = ones.numpy()
np_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)