In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(size=(3,4,5))
x

tensor([[[0.9917, 0.7013, 0.5787, 0.4817, 0.3039],
         [0.0102, 0.9716, 0.9509, 0.5484, 0.9454],
         [0.4547, 0.5416, 0.2677, 0.7927, 0.0616],
         [0.3963, 0.9071, 0.8776, 0.0975, 0.1859]],

        [[0.8254, 0.6537, 0.9554, 0.4736, 0.7361],
         [0.8345, 0.0528, 0.6523, 0.2825, 0.5498],
         [0.9004, 0.6565, 0.9810, 0.1030, 0.2391],
         [0.7143, 0.1697, 0.1143, 0.8218, 0.7974]],

        [[0.8292, 0.0492, 0.0805, 0.0327, 0.6030],
         [0.4760, 0.5971, 0.8103, 0.6565, 0.6479],
         [0.7836, 0.5727, 0.3944, 0.6659, 0.5428],
         [0.5545, 0.7863, 0.0024, 0.8609, 0.4719]]])

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x.resize_(6,10)

tensor([[0.9917, 0.7013, 0.5787, 0.4817, 0.3039, 0.0102, 0.9716, 0.9509, 0.5484,
         0.9454],
        [0.4547, 0.5416, 0.2677, 0.7927, 0.0616, 0.3963, 0.9071, 0.8776, 0.0975,
         0.1859],
        [0.8254, 0.6537, 0.9554, 0.4736, 0.7361, 0.8345, 0.0528, 0.6523, 0.2825,
         0.5498],
        [0.9004, 0.6565, 0.9810, 0.1030, 0.2391, 0.7143, 0.1697, 0.1143, 0.8218,
         0.7974],
        [0.8292, 0.0492, 0.0805, 0.0327, 0.6030, 0.4760, 0.5971, 0.8103, 0.6565,
         0.6479],
        [0.7836, 0.5727, 0.3944, 0.6659, 0.5428, 0.5545, 0.7863, 0.0024, 0.8609,
         0.4719]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
y = torch.randint(9, size=(10,))
y

tensor([2, 4, 3, 1, 7, 0, 0, 6, 2, 0])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
x_plus_y = x+y
x_plus_y

tensor([[2.9917, 4.7013, 3.5787, 1.4817, 7.3039, 0.0102, 0.9716, 6.9509, 2.5484,
         0.9454],
        [2.4547, 4.5416, 3.2677, 1.7927, 7.0616, 0.3963, 0.9071, 6.8776, 2.0975,
         0.1859],
        [2.8254, 4.6537, 3.9554, 1.4736, 7.7361, 0.8345, 0.0528, 6.6523, 2.2825,
         0.5498],
        [2.9004, 4.6565, 3.9810, 1.1030, 7.2391, 0.7143, 0.1697, 6.1143, 2.8218,
         0.7974],
        [2.8292, 4.0492, 3.0805, 1.0327, 7.6030, 0.4760, 0.5971, 6.8103, 2.6565,
         0.6479],
        [2.7836, 4.5727, 3.3944, 1.6659, 7.5428, 0.5545, 0.7863, 6.0024, 2.8609,
         0.4719]])

In [7]:
x_plus_y.shape

torch.Size([6, 10])

In [8]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
new_mtrx = torch.matmul(x_plus_y, x_plus_y.T)
new_mtrx

tensor([[156.0475, 148.8332, 155.8086, 149.9396, 150.8910, 149.7608],
        [148.8332, 143.1236, 149.2867, 142.9284, 144.2025, 143.2458],
        [155.8086, 149.2867, 157.7687, 151.3976, 151.5145, 150.6014],
        [149.9396, 142.9284, 151.3976, 146.0869, 145.5968, 144.9991],
        [150.8910, 144.2025, 151.5145, 145.5968, 147.2026, 145.4333],
        [149.7608, 143.2458, 150.6014, 144.9991, 145.4333, 145.2109]])

In [9]:
new_mtrx.shape

torch.Size([6, 6])

In [10]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
#drv_y(x) = 3x**2, drv_y(z) = 1, drv_y(t) = 75  => in point (1, 0.5, 2) deriv = (3, 1, -75)
point_x = torch.tensor([1.], requires_grad=True)
point_z = torch.tensor([0.5], requires_grad=True)
point_t = torch.tensor([2.], requires_grad=True)
ort_1 = torch.ones(size=(1,), requires_grad=True)

In [11]:
h = point_x**3 + point_z - 75 * point_t

In [12]:
h.backward(ort_1)

In [18]:
print(f' y function derivative in point: \n x = {point_x.grad}\n z = {point_z.grad}\n t = {point_t.grad}')

 y function derivative in point: 
 x = tensor([3.])
 z = tensor([1.])
 t = tensor([-75.])


In [14]:
# 8. Создайте единичный тензор размера 5x6
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
# 9. Переведите его в формат numpy
np_arr = ones.numpy()
np_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)